---
name: Bug report
about: Create a report to help us improve
title: ""
labels: bug, review required
assignees: ""

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here.
    validations:
      required: false
