---
name: Suggestion
about: Suggest new features or an idea for OSORI
title: ""
labels: suggestion, review required
assignees: ""

body:
  - type: textarea
    id: description
    attributes:
      label: "Describe an idea or new features"
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: Add any other context about the feature request here.
    validations:
      required: false
